BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "manager_pass" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"nome"	TEXT,
	"senha"	TEXT,
	"email"	TEXT,
	"obs"	TEXT
);
CREATE TABLE IF NOT EXISTS "USERS" (
	"IDUSER"	INTEGER  PRIMARY KEY AUTOINCREMENT,
	"user"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"TYPE_US"	INTEGER
);



